# Project information
site_name: Notes
site_url: https://hslima00.github.io/Notes/
site_description: A handy place to create all kinds of memos and annotations!
site_author: Hugo Lima
# Repository
repo_name: hslima00/Notes
copyright: Copyright &copy; 2022 Hugo Lima



# Configuration
theme:
  name: material
  custom_dir: material
  language: pt
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.tabs
    - content.code.annotate
  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  #language: pt
    #- navigation.instant
  palette:
    scheme: slate
    primary: black
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: fontawesome/solid/laptop-code


# Plugins
plugins:
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true      
      type: date
      locale: pt
  - search
  - include-markdown
  - minify:
        minify_html: true
        htmlmin_opts:
            remove_comments: true
      
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hslima00
#    - icon: fontawesome/brands/youtube
#      link: https://www.youtube.com/channel/UCzgyG0bgwcu14KuS9sbUHMw/playlists?view_as=subscriber
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/javierobcn
#    - icon: fontawesome/brands/linkedin
#      link: https://linkedin.com/in/squidfunk/
#    - icon: fontawesome/brands/instagram
#      link: https://instagram.com/squidfunk
 # disqus: javieranto

# Extensions
markdown_extensions:
  - pymdownx.progressbar
  - abbr
  - attr_list
  - def_list
  - footnotes
  - pyembed.markdown
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: hslima00
      repo: mkdocs-material
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - md_in_html
  - markdown_blockdiag:
      format: svg
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      #linenums_style: pymdownx-inline 
  - toc:
      permalink: true
      title: Nesta Página
      #permalink_title: Anchor link to this section for reference
      #toc_depth: 3
  - extra
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.betterem:
        smart_enable: all
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
        custom_checkbox: true
  - markdown_include.include
  - pymdownx.arithmatex:
        generic: true



extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - stylesheets/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Google Analytics
# google_analytics:
#   - UA-30695368-1
#   - auto