# Project information
site_name: Notes
site_url: https://hslima00.github.io/Notes/
site_description: A handy place to create all kinds of memos and annotations!
site_author: Hugo Lima
# Repository
repo_name: hslima00/Notes
copyright: Copyright &copy; 2022 Hugo Lima

docs_dir: Markdown
theme:
  name: material
  custom_dir: docs/theme
  icon:
    logo: material/book-open-page-variant
    annotation: material/chevron-right-circle
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  font:
    text: Ubuntu Mono
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.tabs.link
    - blog
    - navigation.footer
    - navigation.indexes
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - attr_list
  - md_in_html
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
        # Add this new fence for blockdiag
        # - name: md-render
        #  class: md-render
        #  format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: hslima00
      repo: notes
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.mark:
  - pymdownx.striphtml:
  #- pymdownx.snippets:
  #    base_path:
  #    - docs/src/markdown/.snippets
  #    - LICENSE.md
  #    auto_append:
  #    - refs.md
  #    check_paths: true
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details: 
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hslima00
extra_css:
  - assets/pymdownx-extras/extra-13d1e30d3e.css
  - assets/stylesheets/custom.7c86dd97.min.css
  - assets/stylesheets/extra.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-d39d49fc.js
  - assets/javascripts/custom.9e5da760.min.js


plugins:
  - awesome-pages
  - search: {}
  - encryptcontent:
      password_file: ../passwords.yml
      global_password: 'teste'
      encrypted_something:
          md-footer__inner: [nav, class]
          md-nav: [nav, class]
      search_index: 'clear'
      mermaid2: False
      hljs: False
      webcrypto: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - mkdocs_pymdownx_material_extras
  - minify:
      minify_html: true
  - blog



      
